### ISSUE TITLE
Url not working?

### ISSUE THREAD

**Issue by Riddalmorning** [circleguard/circleguard#110]
So, i tried this: circleguard://m=240011&u=913428&m1=HDDT
and it output me this:
```
[DEBUG] 2020/12/11 03:26:12.0170 Loading ReplayMap(map_id=240011,user_id=913428,mods=HDDT,cache=None,loaded=False) (circleguard.loadables.ReplayMap, loadables.py:907)
[ERROR] 2020/12/11 03:26:12.0175 sys.excepthook error
Type: <class 'TypeError'>
Value: %d format: a number is required, not str
Traceback:   File "main.py", line 145, in run_with_except_hook
  File "threading.py", line 870, in run
  File "main.py", line 182, in run_server_socket
  File "gui\circleguard_window.py", line 204, in url_scheme_called
  File "site-packages\circleguard\circleguard.py", line 448, in load
  File "site-packages\circleguard\loadables.py", line 915, in load
  File "site-packages\circleguard\loader.py", line 124, in wrapper
  File "site-packages\circleguard\loader.py", line 278, in replay_info
  File "logging\__init__.py", line 1444, in log
  File "logging\__init__.py", line 1514, in _log
  File "logging\__init__.py", line 1524, in handle
  File "logging\__init__.py", line 1586, in callHandlers
  File "logging\__init__.py", line 894, in handle
  File "gui\circleguard_window.py", line 35, in emit
  File "logging\__init__.py", line 869, in format
  File "logging\__init__.py", line 608, in format
  File "logging\__init__.py", line 369, in getMessage

 (circleguard_gui, main.py:129)
Traceback (most recent call last):
  File "main.py", line 145, in run_with_except_hook
  File "threading.py", line 870, in run
  File "main.py", line 182, in run_server_socket
  File "gui\circleguard_window.py", line 204, in url_scheme_called
  File "site-packages\circleguard\circleguard.py", line 448, in load
  File "site-packages\circleguard\loadables.py", line 915, in load
  File "site-packages\circleguard\loader.py", line 124, in wrapper
  File "site-packages\circleguard\loader.py", line 278, in replay_info
  File "logging\__init__.py", line 1444, in log
  File "logging\__init__.py", line 1514, in _log
  File "logging\__init__.py", line 1524, in handle
  File "logging\__init__.py", line 1586, in callHandlers
  File "logging\__init__.py", line 894, in handle
  File "gui\circleguard_window.py", line 35, in emit
  File "logging\__init__.py", line 869, in format
  File "logging\__init__.py", line 608, in format
  File "logging\__init__.py", line 369, in getMessage
TypeError: %d format: a number is required, not str
```

**Comment by tybug** [comment]
Ironically, this should only happen if you have your log level set to TRACE, so an easy workaround for now is to set your log level to anything else. The reason this happened is some of our logging expects an integer value but we were giving it a string. Fixed by 3df35156bd4b4499f346e2e56033cf0474d779a1
