### ISSUE TITLE
error parsing beatmap 177

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#114]
Dunno if this is the same as #107, but here's another one I came across
```
[ERROR] 2020/12/13 17:54:06.0348 Error while running circlecore. Please report this to the developers through discord or github.
 (circleguard_gui, main_tab.py:516)
Traceback (most recent call last):
  File "site-packages\slider\library.py", line 256, in lookup_by_id
  File "site-packages\slider\library.py", line 224, in _raw_read_beatmap
KeyError: 177

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\slider\beatmap.py", line 757, in _get_as_str
KeyError: 'PreviewTime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\main_tab.py", line 434, in run_circleguard
  File "site-packages\circleguard\circleguard.py", line 211, in ur
  File "site-packages\circleguard\loadables.py", line 652, in beatmap
  File "site-packages\slider\library.py", line 260, in lookup_by_id
  File "site-packages\slider\library.py", line 408, in download
  File "site-packages\slider\beatmap.py", line 1936, in parse
  File "site-packages\slider\beatmap.py", line 784, in _get_as_int
  File "site-packages\slider\beatmap.py", line 760, in _get_as_str
ValueError: missing field 'PreviewTime' in section 'General'
```
This happens when investigating the user with the id 1388767, no idea which replay or map specifically it is

**Comment by tybug** [comment]
slider can't deal with really old beatmap file formats currently https://github.com/llllllllll/slider/issues/79

**Comment by tybug** [comment]
will be fixed by the next slider release (see https://github.com/llllllllll/slider/pull/87)
