### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#117]
error while loading a replay: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "gui\main_tab.py", line 341, in run_circleguard
  File "site-packages\circleguard\circleguard.py", line 448, in load
  File "site-packages\circleguard\loadables.py", line 1025, in load
  File "site-packages\circleparse\replay.py", line 221, in parse_replay_file
  File "site-packages\circleparse\replay.py", line 205, in parse_replay
  File "site-packages\circleparse\replay.py", line 61, in __init__
  File "site-packages\circleparse\replay.py", line 74, in parse_replay_and_initialize_fields
  File "site-packages\circleparse\replay.py", line 151, in parse_play_data
TypeError: 'NoneType' object is not subscriptable
The replay Unloaded ReplayPath at [replay path].osr has been skipped because of this.

Replays that this happens to:
https://myangel.aku.lu/4RbDQBgU.osr
https://myangel.aku.lu/me2cIis6.osr
https://myangel.aku.lu/0rN3jDwS.osr
https://myangel.aku.lu/gQtIOdG9.osr

**Comment by tybug** [comment]
The first one is a mania replay, we only support std. I suspect the other replays have the same issue.

**Comment by myangelaku** [comment]
> 
> 
> The first one is a mania replay, we only support std. I suspect the other replays have the same issue.

Ahhh, that explains it. Still, an error message stating that would be nice ^^

**Comment by tybug** [comment]
agreed, fixed in f6741d53bd36e5c16a9523d87e2916209591bb80
