### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#118]
```
[ERROR] 2020/12/23 21:07:28.0721 Error while running circlecore. Please report this to the developers through discord or github.
 (circleguard_gui, main_tab.py:516)
Traceback (most recent call last):
  File "site-packages\slider\library.py", line 256, in lookup_by_id
  File "site-packages\slider\library.py", line 224, in _raw_read_beatmap
KeyError: 1680610

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\main_tab.py", line 434, in run_circleguard
  File "site-packages\circleguard\circleguard.py", line 211, in ur
  File "site-packages\circleguard\loadables.py", line 652, in beatmap
  File "site-packages\slider\library.py", line 260, in lookup_by_id
  File "site-packages\slider\library.py", line 408, in download
  File "site-packages\slider\beatmap.py", line 2026, in parse
  File "site-packages\slider\beatmap.py", line 372, in parse
  File "site-packages\slider\beatmap.py", line 676, in _parse
OverflowError: Python int too large to convert to C int
```

The replay that caused this COULD be the following
https://myangel.aku.lu/hJUIVEiJ.osr

**Comment by tybug** [comment]
of course it's on aleph naught...I blame aspire maps using crazy values for this. https://github.com/llllllllll/slider/issues/83
