### ISSUE TITLE
error while loading a replay: list index out of range

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#133]
```
error while loading a replay: list index out of range
Traceback (most recent call last):
  File "gui\main_tab.py", line 341, in run_circleguard
  File "site-packages\circleguard\circleguard.py", line 460, in load
  File "site-packages\circleguard\loadables.py", line 1040, in load
  File "site-packages\circleguard\loadables.py", line 680, in _process_replay_data
IndexError: list index out of range
The replay Unloaded ReplayPath at C:\osu!\Data\r\281d3ff0cb371def33dfd925ff178771-131593798692699926.osr has been skipped because of this.
```
[Replay](https://myangel.aku.lu/Hfkcc7us.osr)

```
error while loading a replay: list index out of range
Traceback (most recent call last):
  File "gui\main_tab.py", line 341, in run_circleguard
  File "site-packages\circleguard\circleguard.py", line 460, in load
  File "site-packages\circleguard\loadables.py", line 1040, in load
  File "site-packages\circleguard\loadables.py", line 680, in _process_replay_data
IndexError: list index out of range
The replay Unloaded ReplayPath at C:\osu!\Data\r\284328f5a4f2b19b2b7dd8f6db2b1c69-131593928050093676.osr has been skipped because of this
```
[Replay](https://myangel.aku.lu/bUl2Lhvv.osr)

```
error while loading a replay: list index out of range
Traceback (most recent call last):
  File "gui\main_tab.py", line 341, in run_circleguard
  File "site-packages\circleguard\circleguard.py", line 460, in load
  File "site-packages\circleguard\loadables.py", line 1040, in load
  File "site-packages\circleguard\loadables.py", line 680, in _process_replay_data
IndexError: list index out of range
The replay Unloaded ReplayPath at C:\osu!\Data\r\28f686fbcde06049407c2ed107d175a3-131483289749602303.osr has been skipped because of this.
```
[Replay](https://myangel.aku.lu/ojwsQWxt.osr)

**Comment by tybug** [comment]
These replays have no replay data (the list of frames is empty, that's why we're getting index errors). If you try to play them in osu this is what osu says as well: `This score has no replay data saved!`. 

I have no idea what happened here but I don't think it was osu!'s fault. I can't find the first score online; https://osu.ppy.sh/users/13947937 has no score on https://osu.ppy.sh/beatmapsets/85251#osu/234378, which are the user and map of the replay respectively (I didn't check the other two). Until I can actually see and download a replay off the osu! site that's broken in this way, I don't want to support this weirdness. Skipping it is good enough.

**Comment by myangelaku** [comment]
> https://osu.ppy.sh/users/13947937 has no score on https://osu.ppy.sh/beatmapsets/85251#osu/234378

Oh, that's because ImDark was my old IGN
And I'm pretty sure I downloaded those with some really weird ways and simply wanted to suggest a nicer error message; skipping them is correct.

**Comment by tybug** [comment]
hmm...I guess there's no harm in throwing a nicer error from circlecore, though this will take a while to propagate to circleguard.
