### ISSUE TITLE
struct.error

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#151]
Replay: https://myangel.aku.lu/p876mf2bwhsn.osr
I'm pretty sure this was played on a 2013 client

```error while loading a replay: unpack_from requires a buffer of at least 8 bytes
Traceback (most recent call last):
  File "gui\main_tab.py", line 346, in run_circleguard
  File "circleguard\circleguard.py", line 460, in load
  File "circleguard\loadables.py", line 1049, in load
  File "osrparse\parse.py", line 51, in parse_replay_file
  File "osrparse\parse.py", line 35, in parse_replay
  File "osrparse\replay.py", line 57, in __init__
  File "osrparse\replay.py", line 71, in _parse_replay_and_initialize_fields
  File "osrparse\replay.py", line 168, in _parse_replay_id
struct.error: unpack_from requires a buffer of at least 8 bytes
The replay Unloaded ReplayPath at E:\f95d0a6f296c5d97f598f21e6b720ed4-131641521088555258.osr has been skipped because of this.```

**Comment by tybug** [comment]
These are almost certainly going to be old replays that were downloaded before score_id was migrated to a long. See also:

![image](https://user-images.githubusercontent.com/31628143/114433358-b852e100-9b8f-11eb-8f96-bc213d60f382.png)
![image](https://user-images.githubusercontent.com/31628143/114433420-cf91ce80-9b8f-11eb-8f71-af1fc978bb39.png)
https://discord.com/channels/532476765860265984/532477317382144001/802396468731183164

we should probably make a proper fix for this.

**Comment by myangelaku** [comment]
> that were downloaded before score_id was migrated to a long

Negative, they're from an osu!/Data/r folder from a 2013 client.

**Comment by tybug** [comment]
that's long before my time - when was score id migrated to a long? 2013 sounds like it could plausibly still have been a short
