### ISSUE TITLE
Lazer replay doesn't load

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#186]
error while loading a replay: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "gui\main_tab.py", line 452, in run_circleguard
  File "circleguard\circleguard.py", line 520, in load
  File "circleguard\loadables.py", line 1326, in load
  File "circleguard\loadables.py", line 1191, in load_from_file
  File "osrparse\replay.py", line 368, in from_path
  File "osrparse\replay.py", line 386, in from_file
  File "osrparse\replay.py", line 403, in from_string
  File "osrparse\replay.py", line 151, in unpack
  File "osrparse\replay.py", line 69, in unpack_play_data
  File "osrparse\replay.py", line 85, in parse_replay_data
ValueError: invalid literal for int() with base 10: ''
The replay Unloaded ReplayPath at C:\Users\chad\AppData\Roaming\osu\exports\MyAngelAku playing [Kyoro] - Mochio- (Snow Note) [Extreme].osr has been skipped because of this.

Replay: https://cdn.discordapp.com/attachments/777228173330612246/976241355611336764/MyAngelAku_playing_Kyoro_-_Mochio-_Snow_Note_Extreme.osr

**Comment by tybug** [comment]
This should be fixed in the next release.
