### ISSUE TITLE
IndexError: list index out of range on Remix 10

### ISSUE THREAD

**Issue by praeludiumOrbis** [circleguard/circleguard#192]
https://osu.ppy.sh/beatmapsets/1503327#osu/3079907

[ERROR] 2023/06/02 20:36:00.0470 Error while running circlecore. Please report this to the developers through discord or github.
 (circleguard_gui, main_tab.py:690)
Traceback (most recent call last):
  File "gui\main_tab.py", line 600, in run_circleguard
  File "circleguard\circleguard.py", line 427, in hits
  File "circleguard\investigations.py", line 272, in hits
  File "circleguard\investigations.py", line 316, in judgments
  File "slider\beatmap.py", line 1967, in hit_objects
  File "slider\beatmap.py", line 2073, in _resolve_stacking
  File "slider\curve.py", line 198, in __call__
  File "slider\utils.py", line 19, in __get__
  File "slider\curve.py", line 192, in _ts
IndexError: list index out of range

**Comment by tybug** [comment]
tracking at https://github.com/llllllllll/slider/issues/110
