### ISSUE TITLE
IndexError while running user check

### ISSUE THREAD

**Issue by tybug** [circleguard/circleguard#35]
```
[ERROR] 2019/08/24 23:32:31.0330 Error while running circlecore. Please report this to the developers through discord or github.
 (__main__, gui.py:552)
Traceback (most recent call last):
  File "gui.py", line 506, in run_circleguard
  File "site-packages\circleguard\circleguard.py", line 356, in load
  File "site-packages\circleguard\replay.py", line 157, in load
  File "site-packages\circleguard\loader.py", line 37, in wrapper
  File "site-packages\circleguard\loader.py", line 160, in user_info
IndexError: list index out of range
```

while running a user check with options userid: 6909105, num_top: 100, num_plays: 100, threshold: 18 it errors on map 777303 because it tries to load the replay for a user that doesn't have a replay on the map, nor does he actually exist (4680149). It's possible that since user infos are loaded at the beginning of the run, the user did indeed have a play in the top 100 on map 777303 but was restricted before we got to it. I tried to reproduce this by running a user check on only that map but could not reproduce, and the api does not return the user in the top plays, agreeing with the website. I find him getting restricted to be the most likely explanation but it's possible the only way to reproduce this issue is run the user check from the beginning (which takes ages.)

**Comment by tybug** [comment]
Closing as outdated / haven't seen this error again
