### ISSUE TITLE
replays on deleted maps cause errors on map lookup

### ISSUE THREAD

**Issue by tybug** [circleguard/circleguard#71]
eg https://cdn.discordapp.com/attachments/539956865245904906/695710230453158008/Ali_Ahmed_-_isoganakya_-_isogu_Stream_Practice_Maps_400BPM_2020-04-03_Osu_-_Copy.osr . This will likely be solved by addressing #59, since users can just have the map downloaded in osu already. In the meantime we could catch the exception thrown by slider and display a "We do not currently support relax checks on deleted beatmaps" message in the terminal.

```python
[22:01:15] Running Relax check
[ERROR] 2020/04/03 22:01:15.0612 Error while running circlecore. Please report this to the developers through discord or github.
 (__main__, gui.py:741)
Traceback (most recent call last):
  File "lib\site-packages\slider\library.py", line 256, in lookup_by_id
  File "lib\site-packages\slider\library.py", line 224, in _raw_read_beatmap
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\circleguard\circleguard.py", line 115, in run
  File "lib\site-packages\slider\library.py", line 260, in lookup_by_id
  File "lib\site-packages\slider\library.py", line 384, in download
  File "lib\site-packages\slider\beatmap.py", line 1630, in parse
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui.py", line 719, in run_circleguard
RuntimeError: generator raised StopIteration
```

Not very high priority since most people care about ranked/loved maps, which will always be available from online.

**Comment by tybug** [comment]
Forget when exactly I added this but here's what gets thrown for this replay instead:

```
The replay Loaded ReplayPath by Ali Ahmed on 0 at /Users/tybug/Desktop/Ali_Ahmed_-_isoganakya_-_isogu_Stream_Practice_Maps_400BPM_2020-04-03_Osu_-_Copy.osr has no map id, so its ur cannot be calculated. This replay has been skipped because of this.
```
I think this is a good enough error message to close this.
